# This file is generated by SciPy's build process
# It contains system_info results at the time of building this package.
from enum import Enum

__all__ = ["show"]
_built_with_meson = True


class DisplayModes(Enum):
    stdout = "stdout"
    dicts = "dicts"


def _cleanup(d):
    """
    Removes empty values in a `dict` recursively
    This ensures we remove values that Meson could not provide to CONFIG
    """
    if isinstance(d, dict):
        return { k: _cleanup(v) for k, v in d.items() if v != '' and _cleanup(v) != '' }
    else:
        return d


CONFIG = _cleanup(
    {
        "Compilers": {
            "c": {
                "name": "gcc",
                "linker": "ld.bfd",
                "version": "11.2.0",
                "commands": "/croot/scipy_1710947333060/_build_env/bin/x86_64-conda-linux-gnu-cc",
                "args": "-march=nocona, -mtune=haswell, -ftree-vectorize, -fPIC, -fstack-protector-strong, -fno-plt, -O2, -ffunction-sections, -pipe, -isystem, /home/fran/anaconda3/envs/tefpa-gw/include, -fdebug-prefix-map=/croot/scipy_1710947333060/work=/usr/local/src/conda/scipy-1.12.0, -fdebug-prefix-map=/home/fran/anaconda3/envs/tefpa-gw=/usr/local/src/conda-prefix, -DNDEBUG, -D_FORTIFY_SOURCE=2, -O2, -isystem, /home/fran/anaconda3/envs/tefpa-gw/include",
                "linker args": "-Wl,-O2, -Wl,--sort-common, -Wl,--as-needed, -Wl,-z,relro, -Wl,-z,now, -Wl,--disable-new-dtags, -Wl,--gc-sections, -Wl,-rpath,/home/fran/anaconda3/envs/tefpa-gw/lib, -Wl,-rpath-link,/home/fran/anaconda3/envs/tefpa-gw/lib, -L/home/fran/anaconda3/envs/tefpa-gw/lib, -march=nocona, -mtune=haswell, -ftree-vectorize, -fPIC, -fstack-protector-strong, -fno-plt, -O2, -ffunction-sections, -pipe, -isystem, /home/fran/anaconda3/envs/tefpa-gw/include, -fdebug-prefix-map=/croot/scipy_1710947333060/work=/usr/local/src/conda/scipy-1.12.0, -fdebug-prefix-map=/home/fran/anaconda3/envs/tefpa-gw=/usr/local/src/conda-prefix, -DNDEBUG, -D_FORTIFY_SOURCE=2, -O2, -isystem, /home/fran/anaconda3/envs/tefpa-gw/include",
            },
            "cython": {
                "name": "cython",
                "linker": "cython",
                "version": "3.0.8",
                "commands": "cython",
                "args": "",
                "linker args": "",
            },
            "c++": {
                "name": "gcc",
                "linker": "ld.bfd",
                "version": "11.2.0",
                "commands": "/croot/scipy_1710947333060/_build_env/bin/x86_64-conda-linux-gnu-c++",
                "args": "-fvisibility-inlines-hidden, -std=c++17, -fmessage-length=0, -march=nocona, -mtune=haswell, -ftree-vectorize, -fPIC, -fstack-protector-strong, -fno-plt, -O2, -ffunction-sections, -pipe, -isystem, /home/fran/anaconda3/envs/tefpa-gw/include, -fdebug-prefix-map=/croot/scipy_1710947333060/work=/usr/local/src/conda/scipy-1.12.0, -fdebug-prefix-map=/home/fran/anaconda3/envs/tefpa-gw=/usr/local/src/conda-prefix, -DNDEBUG, -D_FORTIFY_SOURCE=2, -O2, -isystem, /home/fran/anaconda3/envs/tefpa-gw/include",
                "linker args": "-Wl,-O2, -Wl,--sort-common, -Wl,--as-needed, -Wl,-z,relro, -Wl,-z,now, -Wl,--disable-new-dtags, -Wl,--gc-sections, -Wl,-rpath,/home/fran/anaconda3/envs/tefpa-gw/lib, -Wl,-rpath-link,/home/fran/anaconda3/envs/tefpa-gw/lib, -L/home/fran/anaconda3/envs/tefpa-gw/lib, -fvisibility-inlines-hidden, -std=c++17, -fmessage-length=0, -march=nocona, -mtune=haswell, -ftree-vectorize, -fPIC, -fstack-protector-strong, -fno-plt, -O2, -ffunction-sections, -pipe, -isystem, /home/fran/anaconda3/envs/tefpa-gw/include, -fdebug-prefix-map=/croot/scipy_1710947333060/work=/usr/local/src/conda/scipy-1.12.0, -fdebug-prefix-map=/home/fran/anaconda3/envs/tefpa-gw=/usr/local/src/conda-prefix, -DNDEBUG, -D_FORTIFY_SOURCE=2, -O2, -isystem, /home/fran/anaconda3/envs/tefpa-gw/include",
            },
            "fortran": {
                "name": "gcc",
                "linker": "ld.bfd",
                "version": "11.2.0",
                "commands": "/croot/scipy_1710947333060/_build_env/bin/x86_64-conda-linux-gnu-gfortran",
                "args": "-fopenmp, -march=nocona, -mtune=haswell, -ftree-vectorize, -fPIC, -fstack-protector-strong, -fno-plt, -O2, -ffunction-sections, -pipe, -isystem, /home/fran/anaconda3/envs/tefpa-gw/include, -fdebug-prefix-map=/croot/scipy_1710947333060/work=/usr/local/src/conda/scipy-1.12.0, -fdebug-prefix-map=/home/fran/anaconda3/envs/tefpa-gw=/usr/local/src/conda-prefix",
                "linker args": "-Wl,-O2, -Wl,--sort-common, -Wl,--as-needed, -Wl,-z,relro, -Wl,-z,now, -Wl,--disable-new-dtags, -Wl,--gc-sections, -Wl,-rpath,/home/fran/anaconda3/envs/tefpa-gw/lib, -Wl,-rpath-link,/home/fran/anaconda3/envs/tefpa-gw/lib, -L/home/fran/anaconda3/envs/tefpa-gw/lib, -fopenmp, -march=nocona, -mtune=haswell, -ftree-vectorize, -fPIC, -fstack-protector-strong, -fno-plt, -O2, -ffunction-sections, -pipe, -isystem, /home/fran/anaconda3/envs/tefpa-gw/include, -fdebug-prefix-map=/croot/scipy_1710947333060/work=/usr/local/src/conda/scipy-1.12.0, -fdebug-prefix-map=/home/fran/anaconda3/envs/tefpa-gw=/usr/local/src/conda-prefix",
            },
            "pythran": {
                "version": "0.15.0",
                "include directory": r"../../_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.12/site-packages/pythran"
            },
        },
        "Machine Information": {
            "host": {
                "cpu": "x86_64",
                "family": "x86_64",
                "endian": "little",
                "system": "linux",
            },
            "build": {
                "cpu": "x86_64",
                "family": "x86_64",
                "endian": "little",
                "system": "linux",
            },
            "cross-compiled": bool("False".lower().replace('false', '')),
        },
        "Build Dependencies": {
            "blas": {
                "name": "mkl-sdl",
                "found": bool("True".lower().replace('false', '')),
                "version": "2023.1",
                "detection method": "pkgconfig",
                "include directory": r"/home/fran/anaconda3/envs/tefpa-gw/include",
                "lib directory": r"/home/fran/anaconda3/envs/tefpa-gw/lib",
                "openblas configuration": "unknown",
                "pc file directory": r"/home/fran/anaconda3/envs/tefpa-gw/lib/pkgconfig",
            },
            "lapack": {
                "name": "mkl-sdl",
                "found": bool("True".lower().replace('false', '')),
                "version": "2023.1",
                "detection method": "pkgconfig",
                "include directory": r"/home/fran/anaconda3/envs/tefpa-gw/include",
                "lib directory": r"/home/fran/anaconda3/envs/tefpa-gw/lib",
                "openblas configuration": "unknown",
                "pc file directory": r"/home/fran/anaconda3/envs/tefpa-gw/lib/pkgconfig",
            },
            "pybind11": {
                "name": "pybind11",
                "version": "2.10.4",
                "detection method": "pkgconfig",
                "include directory": r"/home/fran/anaconda3/envs/tefpa-gw/include",
            },
        },
        "Python Information": {
            "path": r"/home/fran/anaconda3/envs/tefpa-gw/bin/python",
            "version": "3.12",
        },
    }
)


def _check_pyyaml():
    import yaml

    return yaml


def show(mode=DisplayModes.stdout.value):
    """
    Show libraries and system information on which SciPy was built
    and is being used

    Parameters
    ----------
    mode : {`'stdout'`, `'dicts'`}, optional.
        Indicates how to display the config information.
        `'stdout'` prints to console, `'dicts'` returns a dictionary
        of the configuration.

    Returns
    -------
    out : {`dict`, `None`}
        If mode is `'dicts'`, a dict is returned, else None

    Notes
    -----
    1. The `'stdout'` mode will give more readable
       output if ``pyyaml`` is installed

    """
    if mode == DisplayModes.stdout.value:
        try:  # Non-standard library, check import
            yaml = _check_pyyaml()

            print(yaml.dump(CONFIG))
        except ModuleNotFoundError:
            import warnings
            import json

            warnings.warn("Install `pyyaml` for better output", stacklevel=1)
            print(json.dumps(CONFIG, indent=2))
    elif mode == DisplayModes.dicts.value:
        return CONFIG
    else:
        raise AttributeError(
            f"Invalid `mode`, use one of: {', '.join([e.value for e in DisplayModes])}"
        )
